# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ci-setup
      - uses: ./.github/actions/ci-checks
      - run: pnpm build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: vue-chessground
          path: ./dist
          if-no-files-found: error
          retention-days: 90
  release:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Release-Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: vue-chessground
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - uses: ./.github/actions/ci-setup
        if: ${{ steps.release.outputs.release_created }}
      - uses: ./.github/actions/ci-checks
        if: ${{ steps.release.outputs.release_created }}
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: vue-chessground
          path: ./dist
        if: ${{ steps.release.outputs.release_created }}
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
